language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t doomias/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true doomias/react-test npm test

after_success:
    - docker build -t doomias/multi-client ./client
    - docker build -t doomias/multi-nginx ./nginx
    - docker build -t doomias/multi-server ./server
    - docker build -t doomias/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push doomias/multi-client
    - docker push doomias/multi-nginx
    - docker push doomias/multi-server
    - docker push doomias/multi-worker
    